#ifndef LANSELECTMODE_H
#define LANSELECTMODE_H

#include "JSystem/J2D/J2DAnimation.h"
#include "JSystem/J2D/J2DPicture.h"
#include "JSystem/J2D/J2DScreen.h"
#include "JSystem/ResTIMG.h"
#include "dolphin/types.h"
#include "macros.h"
#include <JSystem/J2D/J2DPane.h>
#include <JSystem/JKernel/JKRArchive.h>

class LANSelectMode { // Autogenerated
public:
    enum Color {
        cLanColor_0,
        cLanColor_1,
        cLanColor_2,
    };

    class Background {
    public:
        Background(JKRArchive *archive) {
            mTransFrame = 0;
            mKeyFrame = 0;
            setup(archive);
        }

        void setup(JKRArchive *);
        void calc();

        void draw(const J2DGrafContext *graf) {
            mScreen.draw(0.0f, 0.0f, graf);
        }

        // Inline/Unused
        ~Background();
    private:
        J2DScreen mScreen;
        J2DAnmTransform *mTrans;
        J2DAnmTextureSRTKey*mTexKey;
        s16 mTransFrame;
        s16 mKeyFrame;
        PLACEHOLDER_BYTES(0x124, 0x128);
    }; // Size: 0x128?

    class Item {
    public:
        
        // Inline/Unused
        Item(u32, J2DScreen *, void *);
        void selectIn();
        void selectOut();
        void unselect();

        virtual void update() {} // 0x802158b0
        virtual void calc(); // 0x80212e50
        virtual bool changeValueUp() { return false; } // 0x80216018
        virtual bool changeValueDown() { return false; } // 0x80216020
        virtual void changeColor(Color); // 0x80212dac

        void changeTex(ResTIMG *paImg) {
            mBasePicture->changeTexture(paImg, 0);
        }        
    protected:
        int mState;
        J2DPane *mBasePane;
        J2DPicture *mBasePicture;
        J2DAnmTransform *mTrans;
        s16 mTransFrame;
    }; // Size: 0x18

    class SelectableItem : public Item {
    public:
        SelectableItem(u32, J2DScreen *, void *, void *, void *, int, int, u32); // 0x80212f00
        bool changeValueUp(); // 0x802132d8
        bool changeValueDown(); // 0x802133c8

        void update(); // 0x802134b4
        void calc(); // 0x8021350c

        // Inline/Unused
        void setMask(u32);
        void setMax(int);

        int get_18() {
            return mIdx;
        }
    protected:
        int mIdx;
        int mMax;
        u32 mMask;
        int _24;
        J2DAnmTransform *mTrans1;
        J2DAnmTransform *mTrans2;
        J2DAnmTextureSRTKey *mTexKey;
        J2DAnmTevRegKey *mKey1;
        J2DAnmTevRegKey *mKey2;
        J2DPane *mLeftPane;
        J2DPane *mRightPane;
        s16 mTransFrame1;
        s16 mTransFrame2;
        s16 mTexFrame;
        s16 mKeyFrame1;
        s16 mKeyFrame2;
    }; // size: 0x50? (padded)

    class SelectableItem1 : public SelectableItem {
    public:
        virtual void changeColor(Color); // 0x80213770
        void calc(); // 0x80213884

        // Inline/Unused 
        SelectableItem1(u32, J2DScreen *, void *, void *, void *, ResTIMG **, int);
    
        // Fabricated Inlines
        void changeImg(ResTIMG **paImg) {
            mTimg = paImg;
            mPicture->changeTexture(mTimg[mIdx], 0);

        }    
    protected:
        J2DPicture *mPicture;
        ResTIMG **mTimg;
    }; // Size: 0x58

    class SelectableItem2 : public SelectableItem {
    public:
        virtual void changeColor(Color); // 0x80213b3c
        void calc(); // 0x80213cc0

        // Inline/Unused
        SelectableItem2(u32, J2DScreen *, void *, void *, void *);
    private:
        J2DPicture *_50;
        J2DPicture *_54;
    };

    class SelectableItemDisp : public SelectableItem {
    public:
        void changeColor(Color); // 0x80214088
        void calc(); // 0x802142ec

        // Inline/Unused
        SelectableItemDisp(u32, J2DScreen *, void *, void *, void *);
    private:
        J2DPicture *mImgL1;
        J2DPicture *mImgL2;
        J2DPicture *mImgSw;
        J2DAnmTevRegKey *mKeyDisp;
        s16 _60;
    }; // Size: 0x64

    class SelectableItemSw : public SelectableItem1 {
    public:
        enum ValueMode {
            cValueMode_0,
            cValueMode_1,
        };
        void changeValueMode(ValueMode); // 0x80213fc0

        ValueMode getValueMode() {
            return mValueMode;
        }

        // Inline/Unused
        SelectableItemSw(u32, J2DScreen *, void *, void *, void *, ResTIMG **, ResTIMG **, int, ResTIMG **, int);
        void setMaskSw(u32);
    private:
        ValueMode mValueMode;
        int mIdxSw;
        int mMaxSw;
        u32 mMaskSw;
        ResTIMG **mValueTimg;
        ResTIMG **mTimgSw;
    }; // Size: 0x70
    
    LANSelectMode(JKRArchive *); // 0x8021462c
    void directView(int); // 0x802158b4
    int calc(); // 0x80215c9c
    void calcAnm(); // 0x80216028
    void draw(const J2DGrafContext *); // 0x802161ac
    void start(bool); // 0x80216214
    void setDisplayMax(); // 0x80216358    
    
private: 
    u32 mState;
    bool _4;
    bool _5;
    Background mBackground;
    J2DScreen mScreen; // foreground?
    J2DAnmBase *mAnm;
    s16 mAnmFrame;
    int mItemIdx;
    u32 mItemMask;
    SelectableItem1 *mModeItem;
    SelectableItem1 *mPowerItem;
    SelectableItem2 *mLapItem;
    SelectableItem1 *mOrderItem;
    SelectableItemSw *mCourseSelectItem;
    SelectableItem1 *mTagItem;
    SelectableItemDisp *mDisplayItem;
    Item *mItem;
    Item *mItems[8];
    ResTIMG *mGameModeImg[3];
    ResTIMG *mPowerImg[4];
    ResTIMG *mOrderImg[2];
    ResTIMG *mCrsOrderImg[7];
    ResTIMG *_2d8;
    ResTIMG *mStageOrderImg[2];
    ResTIMG *mSelectImg[2];
    ResTIMG *mCrsNameImg[16];
    ResTIMG *mMapImg[6];
    ResTIMG *mTagImg[2];
    PLACEHOLDER_BYTES(0x34c, 0x350);
}; // class LANSelectMode

#endif // LANSELECTMODE_H
