#ifndef GOAL2D_H
#define GOAL2D_H

#include "JSystem/JKernel/JKRHeap.h"

#include "JSystem/JORReflexible.h"
#include "Kaneshige/HioMgr.h"


class Goal2DParam : public JORReflexible {
public:
    // Inline/Unused
    Goal2DParam();
    virtual ~Goal2DParam() {}
};

class Goal2DHioNode : public HioNode {
public:
    Goal2DHioNode();
    virtual ~Goal2DHioNode() {}

    Goal2DParam mParam;
};

class Goal2D { // Autogenerated
public:
    Goal2D(JKRHeap *); // 0x80132758
    void init(); // 0x801330ec
    void drawGoal(); // 0x80133224
    void drawRetire(); // 0x801333a0
    void calc(); // 0x80133514
    void sequenceGP(); // 0x80133cc8
    void sequenceVS(); // 0x80133cf4
    void sequenceTA(); // 0x80133f58
    void sequenceMG(); // 0x80133f7c
    void setVSMGRank(); // 0x80134128
    static bool mDrawEndFlag; // 0x80416290
    // Inline/Unused
    ~Goal2D();

    void reset() { init(); }
    int getAnmFrame(int status) const { return mAnmFrame[status*4]; }
private:
    PLACEHOLDER_BYTES(0, 0xb0);
    int mAnmFrame[4]; // b0 TODO: check size/is this part of a sub struct
    PLACEHOLDER_BYTES(0xc0, 0xec);
}; // class Goal2D
#endif // GOAL2D_H
