#ifndef LANNUM2D_H
#define LANNUM2D_H

#include "JSystem/JKernel/JKRHeap.h"

#include "JSystem/JORReflexible.h"
#include "Kaneshige/HioMgr.h"

class LANNum2DParam : public JORReflexible {
public:
    // Inline/Unused
    LANNum2DParam();
    virtual ~LANNum2DParam() {}
};

class LANNum2DHioNode : public HioNode {
public:
    LANNum2DHioNode();
    virtual ~LANNum2DHioNode() {}

    LANNum2DParam mParam;
};

class LANNum2D { // Autogenerated
public:
    LANNum2D(JKRHeap *); // 0x80195a90
    void setDraw1(); // 0x801961c8
    void setDraw2(); // 0x80196918
    void setDraw4(); // 0x80197090
    void init(); // 0x80197840
    void draw(); // 0x80197934
    void calc(); // 0x80197a58
    void start(); // 0x80197b4c
    void start2(); // 0x80197c88
    // Inline/Unused
    ~LANNum2D();

    void reset() { init(); }
private:
    PLACEHOLDER_BYTES(0, 0x10c);
}; // class LANNum2D
#endif // LANNUM2D_H
