#ifndef LANRESULT2D_H
#define LANRESULT2D_H

#include "JSystem/JKernel/JKRHeap.h"

#include "JSystem/JORReflexible.h"
#include "Kaneshige/HioMgr.h"

class LANResult2DParam : public JORReflexible {
public:
    // Inline/Unused
    LANResult2DParam();
    virtual ~LANResult2DParam() {}
};

class LANResult2DHioNode : public HioNode {
public:
    LANResult2DHioNode();
    virtual ~LANResult2DHioNode() {}

    LANResult2DParam mParam;
};

class LANResult2D { // Autogenerated
public:
    LANResult2D(JKRHeap *); // 0x80195358
    void init(); // 0x801954a8
    void draw(); // 0x80195554
    void calc(); // 0x801955f0
    void start(int); // 0x80195664
    // Inline/Unused
    ~LANResult2D();

    void reset() { init(); }
private:
    PLACEHOLDER_BYTES(0, 0x1c);
}; // class LANResult2D
#endif // LANRESULT2D_H
