#ifndef LAPGHOST2D_H
#define LAPGHOST2D_H

#include "JSystem/JKernel/JKRHeap.h"

#include "Kaneshige/RaceTime.h"

class LapGhost2D { // Autogenerated
public:
    LapGhost2D(JKRHeap *); // 0x801949c4
    void init(); // 0x80194b58
    void draw(); // 0x80194bac
    void calc(); // 0x80194c38
    void start(RaceTime, int); // 0x80194d08
    // Inline/Unused
    ~LapGhost2D();
}; // class LapGhost2D
#endif // LAPGHOST2D_H
