#ifndef MOTOR_H
#define MOTOR_H

#include "types.h"
#include "JSystem/JKernel/JKRHeap.h"
#include "JSystem/JORReflexible.h"
#include "Kaneshige/HioMgr.h"
#include "Osako/kartPad.h"

class MotorParam : public JORReflexible {
public:
    // Inline/Unused
    MotorParam();
    virtual ~MotorParam() {}
};

class MotorHioNode : public HioNode {
public:
    MotorHioNode();
    virtual ~MotorHioNode() {}

    MotorParam mParam;
};

class Motor { // Autogenerated
public:
    Motor(JKRHeap *); // 0x801304d8
    void init(); // 0x801305c4
    ~Motor(); // 0x80130668
    void exec(); // 0x8013073c
    void triggerWave(KartGamePad *, int); // 0x80130ad8
    void powerWave(KartGamePad *, f32, u8, u8); // 0x80130b50
    void stop(); // 0x80130cbc
    static const char *mPatternWave[26]; // 0x803942e8
    // Inline/Unused
    void loopWave(KartGamePad *, int);
    void loopWave(KartGamePad *, char *);
    void checkLoop(int, const char *);
    void triggerWave(KartGamePad *, char *);
}; // class Motor
#endif // MOTOR_H
