#ifndef PAUSE2D_H
#define PAUSE2D_H

#include "JSystem/JKernel/JKRHeap.h"
#include "JSystem/JORReflexible.h"
#include "Kaneshige/HioMgr.h"
#include "Osako/kartPad.h"

class Pause2DParam : public JORReflexible {
public:
    // Inline/Unused
    Pause2DParam();
    virtual ~Pause2DParam() {}
};

class Pause2DHioNode : public HioNode {
public:
    Pause2DHioNode();
    virtual ~Pause2DHioNode() {}

    Pause2DParam mParam;
};

class Pause2D { // Autogenerated
public:
    enum PauseStatus {

    };

    Pause2D(JKRHeap *); // 0x8013554c
    void init(); // 0x80136308
    void draw(); // 0x801364d0
    void calc(KartGamePad *); // 0x8013653c
    void selectorGP(KartGamePad *); // 0x8013672c
    void selectorVS(KartGamePad *); // 0x80136854
    void selectorTA(KartGamePad *); // 0x801369d4
    void selectorMG(KartGamePad *); // 0x80136b54
    void selectorCommon(); // 0x80136cec
    void setDrawGP(); // 0x80136d34
    void setDrawVS(); // 0x80136ee4
    void setDrawTA(); // 0x80137408
    void setDrawMG(); // 0x8013792c
    void setDrawCommon(); // 0x80137ff4
    void getScale(int); // 0x801381b4
    static int getPauseSelector(); // 0x801381fc
    static PauseStatus getPauseStatus(); // 0x80138204
    static void setPauseStatus(PauseStatus); // 0x8013820c
    void setPadText(); // 0x80138214
    static int mPauseSelector; // 0x804162b8
    static PauseStatus mStatus; // 0x804162bc
    // Inline/Unused
    ~Pause2D();
    static void *mLineTag;
    static void *mPrintMessageTag;
    static void *mStarTag;
    static void *mStarDrawTag;
}; // class Pause2D
#endif // PAUSE2D_H
