#ifndef SCENETITLE_H
#define SCENETITLE_H

#include "JSystem/JORReflexible.h"
#include "Kameda/Scene.h"

class SceneTitleParam : public JORReflexible {
public:
    SceneTitleParam();
    virtual ~SceneTitleParam() {}

    static u8 mDemoType;
};

class SceneTitle : public Scene { // Autogenerated
public:
    SceneTitle(JKRArchive *, JKRHeap *); // 0x8013c6e0
    virtual ~SceneTitle(); // 0x8013caf0
    virtual void init(); // 0x8013c9a8
    virtual void draw(); // 0x8013cb6c
    virtual void calc(); // 0x8013cbd0

    void fadeIn(); // 0x8013cd44
    void title(); // 0x8013cda8
    void card(); // 0x8013cfa8
    void titleMenu(); // 0x8013d01c
    void nextScene(); // 0x8013d344
    void demo(); // 0x8013d484
    void titleMenuAnm(); // 0x8013d6a0

    static const u64 mTitleBckBrkTag[13]; // 0x8036dac8
    static int mDemoFlag; // 0x804145b0
   
}; // class SceneTitle
// Outside class members

#endif // SCENETITLE_H
