#ifndef SCENELANENTRY_H
#define SCENELANENTRY_H

#include "Kameda/Scene.h"

// Makes use of LANBackground

class SceneLanEntry : public Scene { // Autogenerated
public:
    class Window {
    public:
        enum Message {

        };

        // Inline/Unused
        void setup(JKRArchive *);
        void open(Message);
        void getBmgMessageID(Message);
        void calc();
        ~Window();
    };

    SceneLanEntry(JKRArchive *, JKRHeap *); // 0x80190d68
    void init(); // 0x80190f18
    ~SceneLanEntry(); // 0x80190f64
    void draw(); // 0x80190fe8
    void debugDraw(); // 0x801910a4
    void calc(); // 0x801917d4
    void start(); // 0x80191c64
    void waitLink(); // 0x80191d38
    void waitIPGet(); // 0x80191dac
    void waitSearch(); // 0x80191eac
    void waitSetup(); // 0x80191f9c
    void waitSleep(); // 0x8019232c
    void waitEnd(); // 0x801923c4
    void waitButton(); // 0x801924d8
    void nextScene(); // 0x80192568
    void backScene(); // 0x801925b8
    void error(Window::Message); // 0x8019260c
    void debug(); // 0x801926b4
    // Inline/Unused
    //void countDownSearchTimer();
}; // class SceneLanEntry

#endif // SCENELANENTRY_H
