#ifndef SCENEMAPSELECT_H
#define SCENEMAPSELECT_H

#include "Kameda/Scene.h"
#include "kartEnums.h"

class SceneMapSelect : public Scene { // Autogenerated
public:
    SceneMapSelect(JKRArchive *, JKRHeap *); // 0x801928dc
    virtual ~SceneMapSelect(); // 0x80193478
    virtual void init(); // 0x80193388
    virtual void draw(); // 0x80193530
    virtual void calc(); // 0x80193600

    struct MapData {
        ECourseID courseID;
        const char *coName;
        const char *copName;
    };

    void reset(); // 0x80192d44
    void map_init(); // 0x80193824
    void map(); // 0x801938dc
    void buttonA(); // 0x80193ccc
    void buttonB(); // 0x80193dec
    void map_end(); // 0x80193e90
    void nextScene(); // 0x80193f78
    void nextBattle(); // 0x8019400c
    void calcAnm(); // 0x801943d0
    void rndRoulette(); // 0x80194620
    
    static const MapData mMapData[6]; // 0x80376310
    static const u64 mMapSelectBckTag[3]; // 0x80376358
    static const u64 mMapBckTag[3]; // 0x80376370
    static const u64 mMapBrkTag[2]; // 0x80376388
    static const u64 mMapBpkTag; // 0x80419af8
}; // class SceneMapSelect
#endif // SCENEMAPSELECT_H
