#ifndef MAPOBJSNOWMAN_H
#define MAPOBJSNOWMAN_H

#include "JSystem/J3D/J3DSkinDeform.h"
#include "JSystem/JKernel/JKRHeap.h"
#include "Kaneshige/Course/CrsData.h"
#include "Sato/J3DAnmObject.h"
#include "Shiraiwa/Objects/MapObjHioNode.h"

class TMapObjSnowMan : public TMapObjHioNode {      // Autogenerated
public:
    TMapObjSnowMan(const CrsData::SObject &);       // 0x802b6e50
    virtual ~TMapObjSnowMan();                      // 0x802b6edc
    virtual void loadAnimation();                   // 0x802b70c4
    virtual void createModel(JKRSolidHeap *, u32);  // 0x802b7050
    virtual void reset();                           // 0x802b6fd4
    virtual void calc();                            // 0x802b7118
    virtual void update();                          // 0x802b711c
    virtual const char *getBmdFileName();           // 0x802b6fac

    static J3DDeformData *sSnowManBlsAnmData;       // 0x80416fc8
    static J3DAnmCluster *sSnowManBlkAnmData;       // 0x80416fcc

    J3DAnmObjCluster _14c;
}; // class MapObjSnowMan
#endif // MAPOBJSNOWMAN_H
