#ifndef MAPOBJWLUARROW_H
#define MAPOBJWLUARROW_H

#include "JSystem/J3D/J3DAnmTransform.h"
#include "JSystem/J3D/J3DMtxCalc.h"
#include "JSystem/JKernel/JKRHeap.h"
#include "Kaneshige/Course/CrsData.h"
#include "Sato/J3DAnmObject.h"
#include "Shiraiwa/Objects/MapObjHioNode.h"

class TMapObjWlArrow : public TMapObjHioNode { // Autogenerated
public:
    TMapObjWlArrow(const CrsData::SObject &);
    virtual ~TMapObjWlArrow();
    virtual void loadAnimation();
    virtual void createModel(JKRSolidHeap *, u32);
    virtual void reset();
    virtual void calc();
    virtual void update();
    virtual const char *getBmdFileName();

    static J3DAnmTextureSRTKey *sWlArrowBtkAnm;             // 0x80416f08
    static J3DAnmTransform *sWlArrowBckAnmTrans;            // 0x80416de0
    static J3DMtxCalc *sWlArrowBckMtxCalc;                  // 0x80416de4

    J3DAnmObjMaterial mAnmObjMat;
}; // class TMapObjWluArrow

class TMapObjWluSearchLight : public TMapObjHioNode {
public:
    TMapObjWluSearchLight(const CrsData::SObject &);
    virtual ~TMapObjWluSearchLight();
    virtual void loadAnimation();
    virtual void createModel(JKRSolidHeap *, u32);
    virtual void reset();
    virtual void calc() {}
    virtual const char *getBmdFileName();

    static J3DAnmTransform *sWlScLightBckAnmTrans;            // 0x80416de0
    static J3DMtxCalc *sWlScLightBckMtxCalc;                  // 0x80416de4
};

#endif // MAPOBJWLUARROW_H
