#ifndef MAPOBJAWARD_H
#define MAPOBJAWARD_H

#include "JSystem/JGeometry/Matrix.h"
#include "JSystem/JGeometry/Vec.h"
#include "JSystem/JParticle/JPAEmitter.h"
#include "JSystem/JSupport/JSUList.h"
#include "Kaneshige/Course/CrsData.h"
#include "Sato/GeographyObj.h"
#include "Sato/J3DAnmObject.h"
#include "Sato/StateObserver.h"
#include "Sato/Objects/GeoItemBox.h"
#include "Shiraiwa/Objects/MapObjDemoObj.h"
#include "Shiraiwa/Objects/MapObjHioNode.h"

// Forward Declarations:
class TMapObjAwardCup;
class TMapObjAwardItemBox;

class TAwardItemBoxSupervisor : public GeoObjSupervisor {
public:
    TAwardItemBoxSupervisor();
    void entry(TMapObjAwardItemBox *);
    void skip();
    bool isRollState();

    virtual ~TAwardItemBoxSupervisor() {} // 0x802cd57c
    virtual void reset() {} // 0x802cd61c
    virtual void calc() {}  // 0x802cd620

    JSUList<TMapObjAwardItemBox> mList;
};

class TAwardCupSupervisor : public GeoObjSupervisor {
public:
    TAwardCupSupervisor() { mList.initiate(); }
    virtual ~TAwardCupSupervisor() {} // 0x802cd624
    virtual void reset() {} // 0x802cd6c4
    virtual void calc() {}  // 0x802cd6c8
    void draw(u32);
    void entry(TMapObjAwardCup *);

private:
    JSUList<TMapObjAwardCup> mList;
};

class TMapObjAwardCup : public TMapObjDemoObj, public StateObserver, public JKRDisposer {
public:
    TMapObjAwardCup(u32);
    virtual ~TMapObjAwardCup() {
        sSupervisor = nullptr;
    }
    virtual void MoveExec(); // 0x802cc610
    virtual void InitExec(); // 0x802cc5a4
    virtual void loadAnimation();
    virtual void createModel(JKRSolidHeap *, u32);
    virtual void reset();
    virtual void calc();
    virtual void update();
    virtual u32 getJ3DModelDataTevStageNum() const { return 0x20000; }
    virtual TAwardCupSupervisor *getSupervisor() { return sSupervisor; }
    virtual const char *getBmdFileName() = 0;
    virtual const char *getBtpFileName() = 0;

    void setOrgMtx(const JGeometry::TPos3f &);
    f32 makeOffset();
    void flyOut(const JGeometry::TVec3f &);
    void skip(const JGeometry::TVec3f &);
    void initFunc_InBox();
    void doFunc_InBox();
    void initFunc_FlyOut();
    void doFunc_FlyOut();
    void initFunc_Roll();
    void doFunc_Roll();
    void rotAnimation(bool);

    static StateFuncSet<TMapObjAwardCup> sTable[3];
    static JGeometry::TVec3f sVelocity0;
    static f32 sAirFriction;
    static f32 sGravity;
    static f32 sScaleVel;
    static s16 sJumpFrame;
    static f32 sRollSpeed;
    static f32 sRollSpeedMax;
    static s16 sRotCycle;
    static s16 sAxisRotCycle;
    static s16 sFlyOutRotCycle;
    static f32 sRotVel0;
    static f32 sRotBrake;
    static s16 sAxisCycleDecel;
    static f32 sOffsetHeight;
    static TAwardCupSupervisor *sSupervisor;
    static J3DAnmTexPattern *sAwardCupBtpAnm;

    void draw(u32); // UNUSED
    //void TMapObjAwardCup::sSidePowDecel;
    //void TMapObjAwardCup::sAxisCycle;

public:
    JSULink<TMapObjAwardCup> _190;          // 0x190 - Guessed linked list type.
    J3DAnmObjMaterial mAnmObjMaterial;      // 0x1a0
    s8 _1c0;                                // 0x1c0 - +3 bytes padding.
    JGeometry::TVec3f mModelZDir;           // 0x1c4
    JGeometry::TVec3f mModelYDir;           // 0x1d0
    JGeometry::TVec3f mModelXDir;           // 0x1dc
    JGeometry::TPos3f _1e8;                 // 0x1e8
    f32 _218;                               // 0x218
    f32 _21c;                               // 0x21c
    s16 _220;                               // 0x220
    s16 _222;                               // 0x222
    s16 _224;                               // 0x224 - +2 bytes padding.
    JGeometry::TVec3f _228;                 // 0x228
    bool mIsCupInBox;                       // 0x234 - Awards ceremony - Cup in item box?
};

class TMapObjAwardItemBox : public TMapObjHioNode, public StateObserver, public JKRDisposer { // Autogenerated
public:
    TMapObjAwardItemBox(const CrsData::SObject &); // 0x802cb76c
    virtual ~TMapObjAwardItemBox(); // 0x802cb9a0
    virtual void reset(); // 0x802cbaa0
    virtual void calc(); // 0x802cbf40
    virtual const char *getBmdFileName() { return GeoItemBox::getBmdName(); } // 0x802cd6cc
    virtual const char *getShadowBmdFileName() { return GeoItemBox::getShadowBmdName(); } // 0x802cd6ec
    virtual void createColModel(J3DModelData *); // 0x802cba78
    virtual void doKartColCallBack(int); // 0x802cbd10

    void skip(); // 0x802cbc34
    void initFunc_Appear(); // 0x802cbf64
    void doFunc_Appear(); // 0x802cbfa4
    void initFunc_Roll(); // 0x802cc050
    void doFunc_Roll(); // 0x802cc0f4
    void rotAnimation(); // 0x802cc114
    void initFunc_Disappear(); // 0x802cc354
    void doFunc_Disappear(); // 0x802cc370
    void initFunc_Hide(); // 0x802cc428
    void doFunc_Hide(); // 0x802cc450

    static const int scIDTable[18]; // 0x80385450
    static StateFuncSet<TMapObjAwardItemBox> sTable[4]; // 0x803a9e10
    static f32 sRollSpeed; // 0x80415480
    static s16 sAppearFrame; // 0x80415484
    static s16 sDisappearFrame; // 0x80415486
    static TAwardItemBoxSupervisor *sSupervisor; // 0x804170f8

    // Inline
    virtual TAwardItemBoxSupervisor *getSupervisor() { return sSupervisor; } // 0x802cb998
    virtual void MoveExec(); // 0x802cbed4
    virtual void InitExec(); // 0x802cbe68

public:
    JSULink<TMapObjAwardItemBox> mLinkAwardItemBox;     // 0x170 - Guessed linked list type.
    JPABaseEmitter *_180[2];                            // 0x180
    TMapObjAwardCup *mAwardCup;                         // 0x188
    JGeometry::TVec3f mModelZDir;                       // 0x18c
    JGeometry::TVec3f mModelYDir;                       // 0x198
    JGeometry::TVec3f mModelXDir;                       // 0x1a4
    f32 _1b0;                                           // 0x1b0
    f32 _1b4;                                           // 0x1b4
    s16 mRandDir;                                       // 0x1b8
}; // Size: 0x1bc

// Mushroom Cup
class TMapObjAwardCupKinoko : public TMapObjAwardCup {
public:
    TMapObjAwardCupKinoko() : TMapObjAwardCup(0xd67) {}
    virtual ~TMapObjAwardCupKinoko() {}
    virtual const char *getBmdFileName() { return "/AwardKinokoCup.bmd"; }
    virtual const char *getBtpFileName() { return "/AwardKinokoCup.btp"; }
};

// Flower Cup
class TMapObjAwardCupFlower : public TMapObjAwardCup {
public:
    TMapObjAwardCupFlower() : TMapObjAwardCup(0xd68) {}
    virtual ~TMapObjAwardCupFlower() {}
    virtual const char *getBmdFileName() { return "/AwardFlowerCup.bmd"; }
    virtual const char *getBtpFileName() { return "/AwardFlowerCup.btp"; }
};

// Star Cup
class TMapObjAwardCupStar : public TMapObjAwardCup {
public:
    TMapObjAwardCupStar() : TMapObjAwardCup(0xd69) {}
    virtual ~TMapObjAwardCupStar() {}
    virtual const char *getBmdFileName() { return "/AwardStarCup.bmd"; }
    virtual const char *getBtpFileName() { return "/AwardStarCup.btp"; }
};

// Special Cup
class TMapObjAwardCupSpecial : public TMapObjAwardCup {
public:
    TMapObjAwardCupSpecial() : TMapObjAwardCup(0xd6a) {}
    virtual ~TMapObjAwardCupSpecial() {}
    virtual const char *getBmdFileName() { return "/AwardSpecialCup.bmd"; }
    virtual const char *getBtpFileName() { return "/AwardSpecialCup.btp"; }
};

// Reverse Cup
class TMapObjAwardCupReverse : public TMapObjAwardCup {
public:
    TMapObjAwardCupReverse() : TMapObjAwardCup(0xd6b) {}
    virtual ~TMapObjAwardCupReverse() {}
    virtual const char *getBmdFileName() { return "/AwardReverseCup.bmd"; }
    virtual const char *getBtpFileName() { return "/AwardReverseCup.btp"; }
};

// All Cup Tour Cup
class TMapObjAwardCupAllTour : public TMapObjAwardCup {
public:
    TMapObjAwardCupAllTour() : TMapObjAwardCup(0xd6c) {}
    virtual ~TMapObjAwardCupAllTour() {}
    virtual const char *getBmdFileName() { return "/AwardAllCupTour.bmd"; }
    virtual const char *getBtpFileName() { return "/AwardAllCupTour.btp"; }
};

#endif // MAPOBJAWARD_H
