#ifndef MAPOBJPAKKUN_H
#define MAPOBJPAKKUN_H

#include "JSystem/J3D/J3DJoint.h"
#include "JSystem/J3D/J3DModel.h"
#include "JSystem/JGeometry/Matrix.h"
#include "JSystem/JGeometry/Vec.h"
#include "JSystem/JKernel/JKRDisposer.h"
#include "JSystem/JKernel/JKRHeap.h"
#include "Kaneshige/Course/CrsData.h"
#include "Sato/GeographyObj.h"
#include "Sato/StateObserver.h"
#include "Shiraiwa/Objects/MapObjHioNode.h"

class TMapObjPakkun;

class TPakkunSupervisor : public GeoObjSupervisor {
public:
    TPakkunSupervisor();
    virtual ~TPakkunSupervisor() {}           // 0x802d03cc
    virtual void reset() {}                   // 0x802d046c
    virtual void calc() {}                    // 0x802d0470
    virtual void thunderDownAll();

    void entry(TMapObjPakkun *);

    JSUList<TMapObjPakkun> mList;
};


class TMapObjPakkunColHead : public TMapObjHioNode {
public:
    TMapObjPakkunColHead() : TMapObjHioNode(0xe81) {
        mBody = nullptr;
    };
    virtual ~TMapObjPakkunColHead() {}                          // 0x802d048c
    virtual void reset();
    virtual void createColModel(J3DModelData *);
    virtual void doKartColCallBack(int);
    virtual void calc();
    virtual void getKartThrowDirPow(JGeometry::TVec3f *, f32 *, int);
    void checkItemHitting();
    virtual const char *getShadowBmdFileName() { return "/Objects/PakkunShadow.bmd"; } // 0x802d051c

    void setScale(const JGeometry::TVec3f &scale);
    bool isDamage();
    void setPosition(const JGeometry::TVec3f &position);

    bool _14c;
    TMapObjPakkun *mBody;
};


// HACK: J3DJointCallBack is a `bool` by default, but for some reason
//       it's used as an `int` here. Declare this so we can use a
//       typecast to force the right type for now.
typedef int (*J3DJointCallBack2)(J3DJoint*, int);

class TMapObjPakkun : public TMapObjHioNode, public StateObserver, JKRDisposer { // Autogenerated
public:
    TMapObjPakkun(const CrsData::SObject &);                    // 0x802cedb8
    virtual ~TMapObjPakkun();                                   // 0x802cef10
    virtual void MoveExec();                                    // 0x802cf400
    virtual void InitExec();                                    // 0x802cf394
    virtual const char *getBmdFileName() { return "/Objects/Pakkun.bmd"; } // 0x802d0474
    virtual void reset();                                       // 0x802ceff4
    virtual void calc();                                        // 0x802cf264
    virtual void loadAnimation();                               // 0x802cf29c
    virtual void createModel(JKRSolidHeap *, u32);              // 0x802cf2d4
    virtual void createColModel(J3DModelData *);                // 0x802cf368
    virtual void doKartColCallBack(int);                        // 0x802cf46c
    virtual TPakkunSupervisor *getSupervisor() { return sSupervisor; }  // 0x802cef08
    void changeDamageProc();                                    // 0x802cf4c8
    void initFunc_Stand();                                      // 0x802cf570
    void doFunc_Stand();                                        // 0x802cf588
    void initFunc_Attack();                                     // 0x802cf674
    void doFunc_Attack();                                       // 0x802cf6ac
    void initFunc_Rest();                                       // 0x802cf7a8
    void doFunc_Rest();                                         // 0x802cf7ac
    void initFunc_Search();                                     // 0x802cf848
    void doFunc_Search();                                       // 0x802cf854
    void turnTo(const JGeometry::TVec3f &, f32);                // 0x802cfa14
    void setCallBack(const char *, J3DJointCallBack2);          // 0x802cfe0c
    static bool rotCallBack(J3DJoint *, int);                   // 0x802cfe64
    static bool headCallBack(J3DJoint *, int);                  // 0x802cff64
    void checkItemHitting();                                    // 0x802d0084
    void initFunc_Damage();                                     // 0x802d017c
    void doFunc_Damage();                                       // 0x802d01c8
    
    static TAnmInfo sAnmInfos[3];                               // 0x803aa430
    static StateFuncSet<TMapObjPakkun> sTable[5];               // 0x803aa4e4
    static const JGeometry::TVec3f scHeadCenterOffset;          // 0x80413ba0
    static f32 sThunderDamageRandeMax;                          // 0x804154c8
    static f32 sTurnPow;                                        // 0x804154cc
    static f32 sTurnPowFar;                                     // 0x804154d0
    static f32 sTurnAttackScale;                                // 0x804154d4
    static s16 sRestFrame;                                      // 0x804154d8
    static s16 sSearchFrame;                                    // 0x804154da
    static const char *scRootJointName;                         // 0x804154dc
    static const char *scHeadJointName;                         // 0x804154e0
    static TPakkunSupervisor *sSupervisor;                      // 0x80417130
    static const s8 sAnmTable[5];                               // 0x8041d3b0
    
    // Inline/Unused
    void changeAllState(u16 state);
    void setRotMtx(int index, Mtx);
    void setHeadPos(Mtx);
    
    virtual u32 getSoundID() const { return 0x10056; }          // 0x802d0480

    JSULink<TMapObjPakkun> mLinkPakkun;     // 0x170
    TAnmPlayer mAnmPlayer;                  // 0x180
    u16 _198;                               // 0x198
    u16 _19a;                               // 0x19a
    f32 _19c;                               // 0x19c
    f32 _1a0;                               // 0x1a0
    s16 mKartIdx;                           // 0x1a4
    s16 _1a6;                               // 0x1a6
    JGeometry::TVec3f _1a8;                 // 0x1a8
    JGeometry::TPos3f _1b4;                 // 0x1b4
    JGeometry::TPos3f _1e4;                 // 0x1e4
    JGeometry::TPos3f _214;                 // 0x214
    TMapObjPakkunColHead *_244;             // 0x244
}; // class MapObjPakkun

#endif // MAPOBJPAKKUN_H
