#ifndef MAPOBJWANWAN_H
#define MAPOBJWANWAN_H

#include "Bando/EngineSound.h"
#include "JSystem/JGeometry/Vec.h"
#include "JSystem/JParticle/JPAEmitter.h"
#include "Kaneshige/Course/CrsGround.h"
#include "Sato/J3DAnmObject.h"
#include "Sato/StateObserver.h"
#include "Sato/StringObj.h"
#include "Shiraiwa/Coord3D.h"
#include "Shiraiwa/Objects/MapObjHioNode.h"
#include "macros.h"
#include "types.h"

class TMapObjWanwan;

inline f32 normalizeRelativeAngle(f32 angle, f32 min, f32 max) {
    if (min >= max) {
        return min;
    }
    for (; angle < min; angle += max - min) {
    }

    for (; angle >= max; angle -= max - min) {
    }

    return angle;
}

class TMapObjWanwanPile : public GeographyObj {
public:
    TMapObjWanwanPile();
    virtual ~TMapObjWanwanPile();
    virtual void doKartColCallBack(int);
    virtual void reset();
    virtual void createColModel(J3DModelData *);
    virtual const char *getBmdFileName();
    virtual void calc() {} // 0x80297c18

    void setPosition(const JGeometry::TVec3f &pos) {
        mPos.set(pos);
    }
private:
    friend class TMapObjWanwan;
};

class TMapObjWanwanChain : public GeographyObj {
public:
    TMapObjWanwanChain(); // 0x802978d4
    virtual ~TMapObjWanwanChain(); // 0x80297948
    virtual void reset(); // 0x802979c8
    virtual void createColModel(J3DModelData *); // 0x80297a18
    virtual const char *getBmdFileName(); // 0x80297a1c
    virtual void setCurrentViewNo(u32); // 0x80297a44

    // Inline
    virtual void calc() {} // 0x80297c1c

    static f32 sChainOneLength; // 0x80415190

    void setPosition(const JGeometry::TVec3f &pos) {
        mPos.set(pos);
    }

    void setPile(TMapObjWanwanPile *pile) {
        mpPile = pile;
    }

private:
    friend class TMapObjWanwan;
    TMapObjWanwanPile *mpPile;
};

class TMapObjWanwan : public TMapObjHioNode, StateObserver { // Autogenerated
public:
    TMapObjWanwan(const CrsData::SObject &); // 0x80294db8
    virtual ~TMapObjWanwan(); // 0x80294f34
    void makeChain(int); // 0x80295054
    void reset(); // 0x80295118
    void getParameters(); // 0x80295230
    void resetPosition(int); // 0x802952e0
    void loadAnimation(); // 0x8029534c
    const char *getShadowBmdFileName(); // 0x802953cc
    void createColModel(J3DModelData *); // 0x802953f4
    void createModel(JKRSolidHeap *, u32); // 0x80295444
    const char *getBmdFileName(); // 0x802955dc
    void doKartColCallBack(int); // 0x80295604
    void setCurrentViewNo(u32); // 0x80295668
    void initFunc_Wait(); // 0x802956c8
    void doFunc_Wait(); // 0x802956cc
    void initFunc_Jump(); // 0x80295738
    void doFunc_Jump(); // 0x802957e0
    void initFunc_Attack(); // 0x802958b0
    void initFunc_Attacked(); // 0x80295ac8
    void doFunc_Attacked(); // 0x80295acc
    void initFunc_Jumped(); // 0x80295b60
    void doFunc_Jumped(); // 0x80295b64
    void setRotate(f32); // 0x80295c1c
    void doFunc_Attack(); // 0x80295d60
    void turnDown(bool); // 0x80295e04
    void initFunc_Walk(); // 0x80295e4c
    void doFunc_Walk(); // 0x80295ec4
    void initFunc_Back(); // 0x80295f54
    void doFunc_Back(); // 0x80295fb8
    void fallDown(s32, bool); // 0x80296054
    void turnTo(); // 0x8029614c
    void jumpStart(JGeometry::TVec3f &, f32); // 0x80296338
    bool isTouchGround(); // 0x80296408
    f32 getCourseHeight(JGeometry::TVec3f &); // 0x8029645c
    f32 getAngleToRand(); // 0x80296494
    f32 getRandRadius(u8, u8); // 0x802965c0
    void getWanwanBackPos(JGeometry::TVec3f *); // 0x80296658
    f32 getAngleToAttack(JGeometry::TVec3f &); // 0x802966c0
    
    int searchTargetKart(); // 0x8029678c
    void calc(); // 0x802967bc
    void update(); // 0x80296a2c
    void chainCorrect(); // 0x80296ae8
    bool checkWanwanHitting(); // 0x80296eb8
    void fixChain(); // 0x80296efc
    void setChainPosition(TMapObjWanwanChain *, JGeometry::TVec3f &, JGeometry::TVec3f &, f32); // 0x802971a0
    void createEmitterOnGround(JPABaseEmitter **, const char *); // 0x802974bc

    virtual void MoveExec(); // 0x80297450
    virtual void InitExec(); // 0x80296720

    static StateFuncSet<TMapObjWanwan> sTable[7]; // 0x803a4400
    static f32 sOffsetHeight; // 0x80415168
    static f32 sJumpHeight; // 0x8041516c
    static f32 sChainBackInside; // 0x80415170
    static s16 sDefaultRingNodeNo; // 0x80415174
    static f32 sAirFriction; // 0x80415178
    static f32 sGravity; // 0x8041517c
    static f32 sItemHitVelScale; // 0x80415180
    static f32 sKartHitVelScale; // 0x80415184
    static f32 sJumpVelY; // 0x80415188
    static s16 sJumpTopFrame; // 0x8041518c
    static J3DAnmTransform *sWanwanBckAnmTrans; // 0x80416de0
    static J3DMtxCalc *sWanwanBckMtxCalc; // 0x80416de4
    static J3DDeformData *sWanwanBlsAnmData; // 0x80416de8
    static J3DAnmCluster *sWanwanBlkAnmData; // 0x80416dec
    static int sChainJointNo; // 0x80416df0
    // Inline/Unused
    void fixPosition();
    void fixWall(JGeometry::TVec3f &, JGeometry::TVec3f &);
    void changeState_Wall(u32);
    void getAngleToKart();
    static int sWanwanChainNum;
    static f32 scChainHalfLength;
    // Inline
    virtual u32 getMotorType() const { return 3; }; // 0x802975cc

private:
    TMapObjWanwanChain *mpaChain[30];
    TMapObjWanwanPile *mpPile;
    f32 mChainLength;
    int mKartNo;
    bool _1dc;
    TFreeMove mFreeMove;
    CrsGround *mpGround;
    f32 _20c;
    s16 mWalkTimer;
    s16 mTimesAttacked;
    s16 mWalkDuration;
    u8 mNumChains;
    f32 _218;
    f32 mAttackAngle; // 21c
    f32 mRotate;
    f32 _224;
    f32 mHeightOffset;
    f32 _22c;
    f32 _230;
    s16 mRingNodeNo;
    ExStringNodeManager *mpStringNodeMgr;
    J3DAnmObjCluster mAnmObjCluster;
    JPABaseEmitter *mpEmitter;
}; // class MapObjWanwan
#endif // MAPOBJWANWAN_H
