#ifndef MAPOBJDESUN_H
#define MAPOBJDESUN_H

#include "JSystem/J3D/J3DAnmTexPattern.h"
#include "JSystem/J3D/J3DAnmTransform.h"
#include "JSystem/J3D/J3DMtxCalc.h"
#include "JSystem/JKernel/JKRHeap.h"
#include "Kaneshige/Course/CrsData.h"
#include "Sato/J3DAnmObject.h"
#include "Shiraiwa/Objects/MapObjHioNode.h"
#include "dolphin/mtx.h"

class TMapObjDeBalloon : TMapObjHioNode {
public:
    TMapObjDeBalloon(const CrsData::SObject &);
    virtual ~TMapObjDeBalloon();
    virtual const char *getBmdFileName() { return "/Objects/DeBalloon1.bmd"; }
    virtual void createModel(JKRSolidHeap *, u32);
    virtual void loadAnimation();
    virtual void update();
    virtual void reset();
    virtual void calc();

    static s16 scFloatStartDeg;
    static f32 sFloatHeight;
    static s16 sFloatSpeed;
    static J3DAnmTexPattern *sDeBalloonBtpAnm;

    J3DAnmObjMaterial mAnmObjMat;

    s16 _16c;
};

class TMapObjDesun : public TMapObjHioNode {                // Autogenerated
public:
    TMapObjDesun(const CrsData::SObject &);                 // 0x802bb674
    virtual ~TMapObjDesun();                                // 0x802bb6f8
    virtual const char *getBmdFileName();                   // 0x802bb788
    virtual void reset();                                   // 0x802bb7b0
    virtual void loadAnimation();                           // 0x802bb804
    virtual void createModel(JKRSolidHeap *, u32);          // 0x802bb850
    virtual void calc();                                    // 0x802bb970

    static J3DAnmTransform *sDesunBckAnmTrans;              // 0x80417030
    static J3DMtxCalc *sDesunBckMtxCalc;                    // 0x80417034

}; // class MapObjDesun

#endif // MAPOBJDESUN_H
