#ifndef MAPOBJSNOWROCK_H
#define MAPOBJSNOWROCK_H

#include "JSystem/J3D/J3DModel.h"
#include "JSystem/JKernel/JKRDisposer.h"
#include "JSystem/JSupport/JSUList.h"
#include "Kaneshige/Course/CrsData.h"
#include "Sato/GeographyObj.h"
#include "Sato/StateObserver.h"
#include "Shiraiwa/Objects/MapObjHioNode.h"

class TMapObjSnowRock;

class TSnowRockSupervisor : public GeoObjSupervisor {
public:
    TSnowRockSupervisor() : GeoObjSupervisor() {
        _24.initiate();
    }
    virtual ~TSnowRockSupervisor() {}
    virtual void reset() {}
    virtual void calc();
    //void entry(TMapObjSnowRock *);

    JSUList<TMapObjSnowRock> _24;
};

class TMapObjSnowRock : public TMapObjHioNode, public StateObserver, JKRDisposer { // Autogenerated
public:
    TMapObjSnowRock(const CrsData::SObject &);          // 0x802add50
    virtual ~TMapObjSnowRock();                         // 0x802ade90
    virtual void MoveExec();                            // 0x802adfdc
    virtual void InitExec();                            // 0x802adf70
    virtual void reset();                               // 0x802ae5c0
    virtual void calc();                                // 0x802ae678
    virtual const char *getBmdFileName();               // 0x802ae048
    virtual void createColModel(J3DModelData *);        // 0x802ae070
    virtual TSnowRockSupervisor *getSupervisor() { return sSupervisor; }
    virtual void doKartColCallBack(int);                // 0x802ae0d8
    void initFunc_Stand();                              // 0x802ae69c
    void doFunc_Stand();                                // 0x802ae6b0
    void initFunc_Break();                              // 0x802aeabc
    void doFunc_Break();                                // 0x802aebf8
    void initFunc_Die();                                // 0x802aec20
    void doFunc_Die();                                  // 0x802aec30
    void setAttacked(const JGeometry::TVec3f &, f32);   // 0x802ae490
    void checkItemHitting();                            // 0x802ae7f8
    void makeBreakEmitter();                            // 0x802aeb20
    void hitCheck(TMapObjSnowRock *);                   // 0x802aec34
    
    static StateFuncSet<TMapObjSnowRock> sTable[3];     // 0x803a6848
    static f32 sGravity;                                // 0x804152a0
    static f32 sStartVel;                               // 0x804152a4
    static TSnowRockSupervisor *sSupervisor;            // 0x80416f38
    
    // Inline/Unused

    //void JSUList<TMapObjSnowRock>::~JSUList();
    //void JSULink<TMapObjSnowRock>::~JSULink();
    

    JSULink<TMapObjSnowRock> _170;
    CrsGround *_180;
    f32 _184;
}; // class MapObjSnowRock

#endif // MAPOBJSNOWROCK_H
