#ifndef MAPOBJMOVEITEMBOX_H
#define MAPOBJMOVEITEMBOX_H

#include "JSystem/JGeometry/Vec.h"
#include "Kaneshige/Course/CrsData.h"
#include "Sato/Objects/GeoItemBox.h"
#include "Sato/StateObserver.h"
#include "Shiraiwa/Coord3DUtil.h"

class TMapObjMoveItemBox : public GeoItemBox, public StateObserver { // Autogenerated
public:
    TMapObjMoveItemBox(const CrsData::SObject &);               // 0x802bd458
    virtual ~TMapObjMoveItemBox();                              // 0x802bd4dc
    virtual void MoveExec();                                    // 0x802bd7b8
    virtual void InitExec();                                    // 0x802bd74c
    virtual void reset();                                       // 0x802bd5a4
    virtual void calc();                                        // 0x802bd824
    virtual void move();                                        // 0x802bd858
    void initFunc_Appear();                                     // 0x802bd960
    virtual void resetPosition();                               // 0x802bd9ec
    void doFunc_Appear();                                       // 0x802bda0c
    void initFunc_Roll();                                       // 0x802bdad8
    void doFunc_Roll();                                         // 0x802bdadc
    void setOpeningPos();                                       // 0x802bdb34
    void initFunc_Disappear();                                  // 0x802bdb78
    void doFunc_Disappear();                                    // 0x802bdbc4
    void initFunc_Hide();                                       // 0x802bdc88
    void doFunc_Hide();                                         // 0x802bdcb0
    void initFunc_RaceEnd();                                    // 0x802bdd0c
    void doFunc_RaceEnd();                                      // 0x802bdd2c

    
    static StateFuncSet<TMapObjMoveItemBox> sTable[5];          // 0x803a8410
    static f32 sHeight;                                         // 0x80415358
    static f32 sRollSpeed;                                      // 0x8041535c
    static s16 sAppearFrame;                                    // 0x80415360
    static s16 sDisappearFrame;                                 // 0x80415362
    static f32 sGravitySize;                                    // 0x80415364
    static f32 sReflectRate;                                    // 0x80415368
    static f32 sAirFriction;                                    // 0x8041536c
    static f32 sFriction;                                       // 0x80415370
    static f32 sJumpPow;                                        // 0x80415374
    // Inline/Unused
    //static sAirFriction;
    //static sVelRingSound;

    TFreeFallShakeSky *mFreeFallShakeSky;           // 0x214
    JPABaseEmitter *mEmitter[2];                    // 0x218
    JGeometry::TVec3f pos;                          // 0x220
    JGeometry::TVec3f vel;                          // 0x22c

}; // class MapObjMoveItemBox

class TMapObjMoveItemBoxLimit : public TMapObjMoveItemBox {
public:
    TMapObjMoveItemBoxLimit(const CrsData::SObject &sObject) : TMapObjMoveItemBox(sObject) {}
    virtual ~TMapObjMoveItemBoxLimit() {}                       // 0x802be254
    virtual void reset();
    virtual void move();
    void fixMoveSphere();
    virtual void doKartColCallBack(int);
    virtual void calc();
    virtual void resetPosition() {}                             // 0x802be250
    
    static f32 sGravitySize;
};
// Outside class members
#endif // MAPOBJMOVEITEMBOX_H
