#ifndef MAPOBJPOIHANA_H
#define MAPOBJPOIHANA_H

#include "JSystem/JGeometry/Matrix.h"
#include "JSystem/JGeometry/Vec.h"
#include "JSystem/JKernel/JKRDisposer.h"
#include "Kaneshige/Course/CrsGround.h"
#include "Sato/GeographyObj.h"
#include "Sato/J3DAnmObject.h"
#include "Sato/StateObserver.h"
#include "Shiraiwa/AnmPlayer.h"
#include "Shiraiwa/Coord3DUtil.h"
#include "Shiraiwa/TKartThrower.h"

class TMapObjPoihana;

class TPoihanaSupervisor : public GeoObjSupervisor {
public:
    TPoihanaSupervisor();
    virtual ~TPoihanaSupervisor() {}                // 0x802a2170
    virtual void reset() {}                         // 0x802a2210
    virtual void calc() {}                          // 0x802a2214
    virtual void thunderDownAll();

    void entry(TMapObjPoihana *);
    
    JSUList<TMapObjPoihana> mList;
}; // class TPoihanaSupervisor

class TMapObjPoihana : public TKartThrower, public StateObserver, JKRDisposer { // Autogenerated
public:
    TMapObjPoihana(const CrsData::SObject &);           // 0x8029f460
    virtual ~TMapObjPoihana();                          // 0x8029f714
    virtual void loadAnimation();                       // 0x8029f8b4
    virtual void createModel(JKRSolidHeap *, u32);      // 0x8029f914
    virtual void reset();                               // 0x8029fb58
    virtual void calc();                                // 0x8029fdf4
    virtual void update();                              // 0x8029faf0
    virtual const char *getBmdFileName();               // 0x8029f864
    virtual const char *getShadowBmdFileName();         // 0x8029f88c
    virtual void createColModel(J3DModelData *);        // 0x8029f98c
    virtual TPoihanaSupervisor *getSupervisor() { return sSupervisor; } // 0x8029f67c
    virtual void getKartThrowDirPow(JGeometry::TVec3f *, f32 *, int);   // 0x802a1d84
    virtual void doKartColCallBack(int);                // 0x8029fe3c
    virtual void getThrowDir(JGeometry::TVec3f *, s16);                 // 0x802a1e10
    virtual s32 getThrowPow() { return _250; };         // 0x802a1e08
    virtual void MoveExec();                            // 0x8029fa84
    virtual void InitExec();                            // 0x8029fa18

    bool isIgnore(int);                                 // 0x802a00a4
    void ignoreKart(int);                               // 0x802a00b8
    void clearAllIgnore();                              // 0x802a00c8
    void initFunc_Walk();                               // 0x802a00ec
    void doFunc_Walk();                                 // 0x802a0154
    void updatePosition();                              // 0x802a0320
    void changeSpeedForWater(f32, f32);                 // 0x802a0414
    int searchKart();                                   // 0x802a0504 // TODO: Confirm return type is correct.
    void changeWalkSpeed(f32, f32);                     // 0x802a062c
    void initFunc_Down();                               // 0x802a06fc
    void doFunc_Down();                                 // 0x802a0a30
    void fixWall(const JGeometry::TVec3f &, const JGeometry::TVec3f &); // 0x802a0b54
    void initFunc_Buried();                             // 0x802a0c74
    void doFunc_Buried();                               // 0x802a0d44
    void initFunc_Wake();                               // 0x802a0dc0
    void doFunc_Wake();                                 // 0x802a0dd8
    void initFunc_Throw();                              // 0x802a0fc0
    void doFunc_Throw();                                // 0x802a0fd0
    void initFunc_Run();                                // 0x802a1044
    void doFunc_Run();                                  // 0x802a1170
    void callWalkSound();                               // 0x802a16d4
    void initFunc_Rest();                               // 0x802a182c
    void doFunc_Rest();                                 // 0x802a19fc

    static TAnmInfo sAnmInfos[3];                         // 0x803a5500
    static StateFuncSet<TMapObjPoihana> sTable[7];        // 0x803a55e4
    static s16 sDownRotFrame;                             // 0x804151f0
    static s16 sDownFrame;                                // 0x804151f2
    static f32 sFirstDownVel;                             // 0x804151f4
    static f32 sFirstDownVelBanana;                       // 0x804151f8
    static f32 sDownGravity;                              // 0x804151fc
    static s16 sWakeRotFrame;                             // 0x80415200
    static f32 sFirstWakeVel;                             // 0x80415204
    static f32 sWakeGravity;                              // 0x80415208
    static f32 sWalkWaterRatio;                           // 0x8041520c
    static f32 sDefaultSearchRadius;                      // 0x80415210
    static f32 sRunSpeedRatio;                            // 0x80415214
    static f32 sRunRotRatio;                              // 0x80415218
    static s16 sKartIgnoreFrame;                          // 0x8041521c
    static s16 sWaterDecelBand;                           // 0x8041521e
    static s16 sReSearchFrame;                            // 0x80415220
    static f32 sRunVelScale;                              // 0x80415224
    static f32 sWalkSpeed;                                // 0x80415228
    static J3DAnmTexPattern *sPoihanaBtpAnm;              // 0x80416ea0
    static f32 sSinkOffset;                               // 0x80416ea4
    static TPoihanaSupervisor *sSupervisor;               // 0x80416ea8
    static const s8 sAnmTable[7];                         // 0x8041ca20

    //friend class TPoihanaSupervisor;

    // Inline/Unused
    // void JSULink<TMapObjPoihana>::~JSULink();
    void changeAllState(u16 value) {
        for (int i = 0; i < 8; i++) {
            mTargetableKarts[i] = 0;
        }
    }

    void changeDownState(u16 value) {
        for (int i = 0; i < 8; i++) {
            if (mTargetableKarts[i] != 0) {
                mTargetableKarts[i] -= value;
            }
        }
    };
    void checkItemHitting();
    // void ignoreUpdate();
    // void thunderDown();
    // void SUList<TMapObjPoihana>::~JSUList();
    // void scHeightOffset;
    // void scColorTypeNum;
    // void scLeftDownFrame;
    // void scRightDownFrame;

    void setAnmTableState(u8 newState) {
        setState(newState);
        const s8 anmNo = sAnmTable[newState];
        if (anmNo != mAnmPlayer.getCurAnmNumber()) {
            mAnmPlayer._11 = anmNo;
            mAnmPlayer._10 = true;
            mAnmPlayer._e |= 1;
        }
    }



    JSULink<TMapObjPoihana> mLinkPoihana;   // 0x170
    J3DAnmObjMaterial mAnmObjMaterial;      // 0x180
    TAnmPlayer mAnmPlayer;                  // 0x1a0
    JGeometry::TVec3f mPoihanaPos;          // 0x1b8 - Gets assigned mPos.
    JGeometry::TVec3f mColPos;              // 0x1c4
    JGeometry::TVec3f _1d0;                 // 0x1d0
    TPathWalk *mPathWalk;                   // 0x1dc
    f32 _1e0;                               // 0x1e0 - Might be a TVec3f?
    f32 _1e4;                               // 0x1e4
    f32 _1e8;                               // 0x1e8
    JGeometry::TRot3f _1ec;                 // 0x1ec
    JGeometry::TPos3f _21c;                 // 0x21c
    f32 _24c;                               // 0x24c
    s32 _250;                               // 0x250
    f32 _254;                               // 0x254 - Toss height?
    f32 mFirstDownVel;                      // 0x258
    bool _25c;                              // 0x25c - Is in water?
    s16 _25e;                               // 0x25e
    s16 _260;                               // 0x260
    s16 mKartSearchCounter;                 // 0x262 - ReSearchFrame Counter
    int mTargetKartIdx;                     // 0x264 - Poihana Targeted Kart index?
    u8 mTargetableKarts[8];                 // 0x268 - Poihana ignore (of some sort?)
    CrsGround *mCrsGround;                  // 0x270
}; // class TMapObjPoihana


#endif // MAPOBJPOIHANA_H
