#ifndef MAPOBJDONKYTREE_H
#define MAPOBJDONKYTREE_H

#include "Kaneshige/Course/CrsData.h"
#include "Sato/GeographyObj.h"
#include "Sato/Objects/GeoTree.h"

class TMapObjDonkyTree : public GeoMarioTree1 { // Autogenerated
public:
    TMapObjDonkyTree(const CrsData::SObject &); // 0x802ad6d8
    virtual ~TMapObjDonkyTree();                // 0x802ad714
    virtual const char *getBmdFileName();       // 0x802ad7b4
    virtual GeoAnmTableEntry *getAnmTbl();      // 0x802ad7dc
    virtual u16 getSizeAnmTbl() { return 8; }   // 0x802ad80c

    static GeoAnmTableEntry sBckAnmTable;       // 0x80415290
}; // class TMapObjDonkyTree


class TMapObjDinoTree : public GeoMarioTree1 {
public:
    TMapObjDinoTree(const CrsData::SObject &);
    virtual ~TMapObjDinoTree();
    virtual void reset();
    virtual const char *getBmdFileName();
    virtual GeoAnmTableEntry *getAnmTbl();
    virtual u16 getSizeAnmTbl() { return 8; }

    static GeoAnmTableEntry sBckAnmTable;
}; // class TMapObjDinoTree

class TMapObjDesertTree : public GeoMarioTree1 {
public:
    TMapObjDesertTree(const CrsData::SObject &);
    virtual ~TMapObjDesertTree();
    virtual void reset();
    virtual const char *getBmdFileName();
    virtual void createColModel(J3DModelData *);
    virtual GeoAnmTableEntry *getAnmTbl() { return nullptr; }
    virtual u16 getSizeAnmTbl() { return 0; }
}; // class TMapObjDesertTree


#endif // MAPOBJDONKYTREE_H
