#ifndef MAPOBJDONKYROCKGEN_H
#define MAPOBJDONKYROCKGEN_H

#include "JSystem/J3D/J3DModel.h"
#include "Kaneshige/Course/CrsData.h"
#include "Sato/GeographyObj.h"
#include "Shiraiwa/Objects/MapObjDonkyRock.h"

class TMapObjDonkyRockGen : public GeographyObj {   // Autogenerated
public:
    TMapObjDonkyRockGen(const CrsData::SObject &);  // 0x8029a6bc
    virtual ~TMapObjDonkyRockGen();                 // 0x8029a770
    virtual void reset();                           // 0x8029a7fc
    virtual void calc();                            // 0x8029a870
    virtual void createColModel(J3DModelData *);    // 0x8029a9b4
    bool appearRock();                              // 0x8029a8c8
    void makeRockObject(int);                       // 0x8029a934
    // Inline

    s32 mSpawnInterval;             // 0x14c
    s32 mRockCount;                 // 0x150
    u32 mSpawnTimer;                // 0x154
    TMapObjDonkyRock **mRocks;      // 0x158
};

#endif // MAPOBJDONKYROCKGEN_H
