#ifndef MAPOBJDONKYROCK_H
#define MAPOBJDONKYROCK_H

#include "Inagaki/GameSoundMgr.h"
#include "JSystem/J3D/J3DModel.h"
#include "JSystem/JGeometry/Vec.h"
#include "JSystem/JKernel/JKRDisposer.h"
#include "JSystem/JKernel/JKRHeap.h"
#include "Kaneshige/Course/CrsData.h"
#include "Sato/GeographyObj.h"
#include "Sato/StateObserver.h"
#include "Shiraiwa/Objects/MapObjHioNode.h"

class TMapObjDonkyRock;

class TDonkyRockSupervisor : public GeoObjSupervisor {
public:
    TDonkyRockSupervisor();                 // 0x8029c034
    virtual ~TDonkyRockSupervisor();        // 0x8029c120
    virtual void reset() { return; }        // 0x8029c1c0
    virtual void calc() { return; }         // 0x8029c1c4
    virtual void thunderDownAll();          // 0x8029c0d8
    void entry(TMapObjDonkyRock *);         // 0x8029c0b0

private:
    JSUList<TMapObjDonkyRock> mList;
};

class TMapObjDonkyRock : public TMapObjHioNode, public StateObserver, JKRDisposer { // Autogenerated
public:
    TMapObjDonkyRock();                                         // 0x8029aac4
    virtual ~TMapObjDonkyRock();                                // 0x8029abc8
    virtual void MoveExec();                                    // 0x8029b030
    virtual void InitExec();                                    // 0x8029afc4
    virtual void loadAnimation();                               // 0x8029aefc
    virtual void createColModel(J3DModelData *);                // 0x8029ad5c
    virtual void reset();                                       // 0x8029aca8
    virtual void calc();                                        // 0x8029b09c
    virtual const char *getBmdFileName();                       // 0x8029ad88
    virtual const char *getShadowBmdFileName();                 // 0x8029adb0
    virtual void createModel(JKRSolidHeap *, u32);              // 0x8029af00
    virtual TDonkyRockSupervisor *getSupervisor() { return sSupervisor; } // 0x8029abc0
    virtual void doKartColCallBack(int);                        // 0x8029bf4c
    void start();                                               // 0x8029add8
    void setObjData(const CrsData::SObject *);                  // 0x8029af30
    void initFunc_Wait();                                       // 0x8029b0d4
    void doFunc_Wait();                                         // 0x8029b0fc
    void initFunc_Fall();                                       // 0x8029b100
    void setStartVel();                                         // 0x8029b164
    void doFunc_Fall();                                         // 0x8029b4c0
    void move_FallDown(JGeometry::TVec3f &);                    // 0x8029b5d0
    void getReflect(JGeometry::TVec3f &, JGeometry::TVec3f &);  // 0x8029bbd4
    void getNodePosition(JGeometry::TVec3f *, u16);             // 0x8029bdd8
    void initFunc_Break();                                      // 0x8029be44
    void doFunc_Break();                                        // 0x8029bf24

    static StateFuncSet<TMapObjDonkyRock> sTable[3];            // 0x803a4ba0
    static f32 sReflectRate;                                    // 0x804151c0
    static f32 sFricRate;                                       // 0x804151c4
    static f32 sGravity;                                        // 0x804151c8
    static f32 sMaxSpeed;                                       // 0x804151cc
    static f32 sRotSpeed;                                       // 0x804151d0
    static f32 sKartDownScale;                                  // 0x804151d4
    static TDonkyRockSupervisor *sSupervisor;                   // 0x80416e50
    

    // Inline/Unused
    //void JSULink<TMapObjDonkyRock>::~JSULink();
    //void JSUList<TMapObjDonkyRock>::~JSUList();
    //void sRockRadius;

public:
    JSULink<TMapObjDonkyRock> _170;         // 0x170
    f32 _180;                               // 0x180
    JGeometry::TVec3f _184;                 // 0x184
    f32 _190;                               // 0x190
    u16 _194;                               // 0x194
    u16 _196;                               // 0x196 - Padding?
    JGeometry::TVec3f _198;                 // 0x198
    GameAudio::RockSoundMgr *mRockSoundMgr; // 0x1a4
    const CrsData::SObject *mGenObjData;    // 0x1a8 - setObjData implies this should be const...
    CrsGround *mCrsGround;                  // 0x1ac
}; // 0x1b0

// Outside class members

#endif // MAPOBJDONKYROCK_H
