#ifndef MAPOBJMONTE_H
#define MAPOBJMONTE_H

#include "JSystem/J3D/J3DMtxCalc.h"
#include "JSystem/JKernel/JKRHeap.h"
#include "Kaneshige/Course/CrsData.h"
#include "Sato/J3DAnmObject.h"
#include "Sato/StateObserver.h"
#include "Shiraiwa/AnmPlayer.h"
#include "Shiraiwa/Objects/MapObjDemoObj.h"
#include "dolphin/types.h"

class TMapObjMonteBase : public TMapObjDemoObj, public StateObserver { // Autogenerated
public:
    TMapObjMonteBase(const CrsData::SObject &);
    ~TMapObjMonteBase();
    virtual void MoveExec();
    virtual void InitExec();
    virtual void reset();
    virtual void loadAnimation();
    virtual void createModel(JKRSolidHeap *, u32);
    virtual void calc();
    virtual const char *getShadowBmdFileName() { return "/Objects/monL_a_sh.bmd"; }
    virtual const char *getBmdFileName() = 0;
    void initFunc_Clapping();
    void doFunc_Clapping();
    void initFunc_Banzai();
    void doFunc_Banzai();

    // Inline/Unused
    void changeAllState(u16);
    
    static TAnmInfo sAnmInfos[2];
    static StateFuncSet<TMapObjMonteBase> sTable[2];
    static const s8 sAnmTable[2];

    TAnmPlayer mAnmPlayer;              // 0x178
    f32 _190;                           // 0x190
};

class TMapObjMonteA : public TMapObjMonteBase {
public:
    TMapObjMonteA(const CrsData::SObject &sObject) : TMapObjMonteBase(sObject) {}
    virtual const char *getBmdFileName() { return "/Objects/monL_a.bmd"; };
};

class TMapObjMonteB : public TMapObjMonteBase {
public:
    TMapObjMonteB(const CrsData::SObject &sObject) : TMapObjMonteBase(sObject) {}
    virtual const char *getBmdFileName() { return "/Objects/monL_b.bmd"; };
};

class TMapObjMonteC : public TMapObjMonteBase {
public:
    TMapObjMonteC(const CrsData::SObject &sObject) : TMapObjMonteBase(sObject) {}
    virtual const char *getBmdFileName() { return "/Objects/monL_c.bmd"; };
};

class TMapObjMonteD : public TMapObjMonteBase {
public:
    TMapObjMonteD(const CrsData::SObject &sObject) : TMapObjMonteBase(sObject) {}
    virtual const char *getBmdFileName() { return "/Objects/monL_d.bmd"; };
};

class TMapObjMonteE : public TMapObjMonteBase {
public:
    TMapObjMonteE(const CrsData::SObject &sObject) : TMapObjMonteBase(sObject) {}
    virtual const char *getBmdFileName() { return "/Objects/monL_e.bmd"; };
};

class TMapObjUkleleMonte : public TMapObjDemoObj {
public:
    TMapObjUkleleMonte(const CrsData::SObject &);
    virtual ~TMapObjUkleleMonte();
    virtual void reset();
    virtual void loadAnimation();
    virtual void createModel(JKRSolidHeap *, u32);
    virtual void calc();
    virtual const char *getShadowBmdFileName() { return "/Objects/monL_a_sh.bmd"; }
    virtual const char *getBmdFileName() { return "/Objects/uklele_monte.bmd"; }

    static J3DAnmTransform *sUkMonteBckAnmTrans;
    static J3DMtxCalc *sUkMonteBckMtxCalc;

    J3DAnmObjTrans *mAnmObjTrans;
};

class TMapObjDanceMonte : public TMapObjDemoObj {
public:
    TMapObjDanceMonte(const CrsData::SObject &);
    virtual ~TMapObjDanceMonte();
    virtual void reset();
    virtual void loadAnimation();
    virtual void createModel(JKRSolidHeap *, u32);
    virtual void calc();
    virtual const char *getShadowBmdFileName() { return "/Objects/monL_a_sh.bmd"; }
    virtual const char *getBmdFileName() = 0;


    static TAnmInfo sAnmInfos[2];
    

    TAnmPlayer mAnmPlayer;          // 0x16c
};

class TMapObjDanceMonteA : public TMapObjDanceMonte {
public:
    TMapObjDanceMonteA(const CrsData::SObject &sObject) : TMapObjDanceMonte(sObject) {}
    virtual const char *getBmdFileName() { return "/Objects/monF_a.bmd"; }
};

class TMapObjDanceMonteB : public TMapObjDanceMonte {
public:
    TMapObjDanceMonteB(const CrsData::SObject &sObject) : TMapObjDanceMonte(sObject) {}
    virtual const char *getBmdFileName() { return "/Objects/monF_b.bmd"; }
};

#endif // MAPOBJMONTE_H
