#ifndef MAPOBJMARE_H
#define MAPOBJMARE_H

#include "JSystem/J3D/J3DAnmTransform.h"
#include "Kaneshige/Course/CrsData.h"
#include "Sato/StateObserver.h"
#include "Shiraiwa/AnmPlayer.h"
#include "Shiraiwa/Objects/MapObjDemoObj.h"

class TMapObjMareBase : public TMapObjDemoObj, public StateObserver { // Autogenerated
public:
    TMapObjMareBase(const CrsData::SObject &);
    virtual ~TMapObjMareBase();
    virtual void MoveExec();
    virtual void InitExec();
    virtual void reset();
    virtual void loadAnimation();
    virtual void createModel(JKRSolidHeap *, u32);
    virtual void calc();
    virtual const char *getShadowBmdFileName() { return "/Objects/mareL_a_sh.bmd"; }
    virtual const char *getBmdFileName() = 0;
    void initFunc_Clapping();
    void doFunc_Clapping();
    void initFunc_Banzai();
    void doFunc_Banzai();

    // Inline/Unused
    void changeAllState(u16);

    static TAnmInfo sAnmInfos[2];
    static StateFuncSet<TMapObjMareBase> sTable[2];
    static const s8 sAnmTable[2];

    TAnmPlayer mAnmPlayer;          // 0x178
    f32 _190;                       // 0x190

}; // class MapObjMareBase

class TMapObjMareA : public TMapObjMareBase {
public:
    TMapObjMareA(const CrsData::SObject &sObject) : TMapObjMareBase(sObject) {}
    virtual const char *getBmdFileName() { return "/Objects/mareL_a.bmd"; }
};

class TMapObjMareB : public TMapObjMareBase {
public:
    TMapObjMareB(const CrsData::SObject &sObject) : TMapObjMareBase(sObject) {}
    virtual const char *getBmdFileName() { return "/Objects/mareL_b.bmd"; }
};

class TMapObjMareC : public TMapObjMareBase {
public:
    TMapObjMareC(const CrsData::SObject &sObject) : TMapObjMareBase(sObject) {}
    virtual const char *getBmdFileName() { return "/Objects/mareL_c.bmd"; }
};

class TMapObjMareWBase : public TMapObjDemoObj {
public:
    TMapObjMareWBase(const CrsData::SObject &);
    virtual ~TMapObjMareWBase();
    virtual void reset();
    virtual void loadAnimation();
    virtual void createModel(JKRSolidHeap *, u32);
    virtual void calc();
    virtual const char *getShadowBmdFileName() { return "/Objects/mareL_a_sh.bmd"; }
    virtual const char *getBmdFileName() = 0;

    static J3DAnmTransform *sMareWBckAnmTrans;
    static J3DMtxCalc *sMareWBckMtxCalc;

    J3DAnmObjTrans *mAnmObjTrans;
};

class TMapObjMareW_A : public TMapObjMareWBase {
public:
    TMapObjMareW_A(const CrsData::SObject &sObject) : TMapObjMareWBase(sObject) {}
    virtual const char *getBmdFileName() { return "/Objects/mareW_a.bmd"; }
};

class TMapObjMareW_B : public TMapObjMareWBase {
public:
    TMapObjMareW_B(const CrsData::SObject &sObject) : TMapObjMareWBase(sObject) {}
    virtual const char *getBmdFileName() { return "/Objects/mareW_b.bmd"; }
};

class TMapObjMareW_C : public TMapObjMareWBase {
public:
    TMapObjMareW_C(const CrsData::SObject &sObject) : TMapObjMareWBase(sObject) {}
    virtual const char *getBmdFileName() { return "/Objects/mareW_c.bmd"; }
};


class TMapObjMareM_A : public TMapObjDemoObj {
public:
    TMapObjMareM_A(const CrsData::SObject &);
    virtual ~TMapObjMareM_A();
    virtual void reset();
    virtual void loadAnimation();
    virtual void createModel(JKRSolidHeap *, u32);
    virtual void calc();
    virtual const char *getShadowBmdFileName() { return "/Objects/mareL_a_sh.bmd"; }
    virtual const char *getBmdFileName() { return "/Objects/mareM_a.bmd"; }

    static J3DAnmTransform *sMareMBckAnmTrans;
    static J3DMtxCalc *sMareMBckMtxCalc;

    J3DAnmObjTrans *mAnmObjTrans;
};

 #endif // MAPOBJMARE_H
